name: Grammar Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: LanguageTool Check
        id: language-tool
        run: |
          echo "${{ steps.extract-body.outputs.body }}" > body.md
          cat ${{ steps.modified-files.outputs.files }} | xargs -I{} sh -c 'languagetool -l en-US -c utf-8 -v {} 2>&1 | grep -v "will be ignored" || true'
        continue-on-error: true
        
      - name: Review LanguageTool errors
        if: ${{ always() }}
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          title: LanguageTool Errors
          body: |
            Here is a list of errors found by LanguageTool: 
